language: android
sudo: false
android:
  components:
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
before_install:
  - chmod +x gradlew
  - git submodule update --init --recursive
install:
  - ./gradlew
script:
  - ./gradlew :library:assembleDebug --stacktrace
  - ./gradlew :sample:assembleDebug --stacktrace
  - ./gradlew :sample:testDebug --stacktrace