language: android
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
before_install:
  - chmod +x gradlew
  - git submodule update --init --recursive
install:
  - ./gradlew
script:
  - ./gradlew clean build jacocoTestReport --stacktrace
after_success:
  - bash <(curl -s https://codecov.io/bash)